import type { Source } from './api'

const defaults = {
  description: null,
  favicon_url: null,
  technologies: [],
  topics: [],
  notes: null,
  pinned: false,
  use_case: null,
  learning_value: 'intermediate',
  updated_at: '',
}

export const MOCK_SOURCES: Source[] = [
  {
    ...defaults,
    id: '1',
    title: 'Building LLM-Powered Applications',
    url: 'https://www.deeplearning.ai/short-courses/langchain-chat-with-your-data/',
    summary: 'A comprehensive guide to building production-ready applications using large language models. Covers RAG patterns, vector databases, and prompt engineering best practices.',
    tags: ['ai', 'llm', 'python'],
    category: 'Course',
    created_at: '2025-01-15',
  },
  {
    ...defaults,
    id: '2',
    title: 'Tailwind CSS Documentation',
    url: 'https://tailwindcss.com/docs',
    summary: 'Official Tailwind CSS documentation covering utility classes, configuration, and responsive design patterns. Essential reference for modern CSS workflows.',
    tags: ['css', 'frontend', 'design'],
    category: 'Documentation',
    created_at: '2025-01-14',
  },
  {
    ...defaults,
    id: '3',
    title: 'Next.js App Router Guide',
    url: 'https://nextjs.org/docs/app',
    summary: 'Complete guide to Next.js App Router, covering server components, streaming, layouts, and the new data fetching patterns.',
    tags: ['react', 'next.js', 'frontend'],
    category: 'Documentation',
    created_at: '2025-01-13',
  },
  {
    ...defaults,
    id: '4',
    title: 'PostgreSQL Performance Tuning',
    url: 'https://www.postgresql.org/docs/current/performance-tips.html',
    summary: 'Advanced PostgreSQL optimization techniques including query planning, indexing strategies, and connection pooling for high-traffic applications.',
    tags: ['database', 'postgresql', 'performance'],
    category: 'Article',
    created_at: '2025-01-12',
  },
  {
    ...defaults,
    id: '5',
    title: 'Vercel AI SDK Documentation',
    url: 'https://sdk.vercel.ai/docs',
    summary: 'The Vercel AI SDK simplifies building AI-powered streaming UIs with React. Supports OpenAI, Anthropic, and other providers.',
    tags: ['ai', 'sdk', 'react'],
    category: 'Documentation',
    created_at: '2025-01-11',
  },
  {
    ...defaults,
    id: '6',
    title: 'System Design Interview Handbook',
    url: 'https://www.techinterviewhandbook.org/system-design/',
    summary: 'Comprehensive guide to system design interviews. Covers distributed systems, scalability, databases, caching, and real-world architecture patterns.',
    tags: ['system design', 'interview', 'architecture'],
    category: 'Article',
    created_at: '2025-01-10',
  },
]
